- syntax/oasis.vim
This pattern will match valid version numbers, including just a single number. Whereas the previous pattern would match numbers that were immediately preceded by a letter, this one will not.
> match versions instead of numbers

- syntax/ocaml.vim
' can appear in OCaml identifiers. Adding it to iskeyword lets vim's word movements work as they do in other languages, and also prevents things like match in match' from being highlighted as keywords (utop already does this correctly).
Thanks for the very useful collection of vimfiles! I really appreciate it.
> Modify syntax file to append ' to iskeyword.

- syntax/ocaml.vim
Use apostrophe as iskeyword only in ocaml files, do not enforce it globally — other languages might use apostrophes as string separators, and "set isk+='" makes word boundary commands needlessly complicated (most notably, cw eating final separator).
> Apply iskeyword apostrophe for ocaml only

- .gitignore
This helps having a clean git status when using pathogen and git
submodules. Moreover, you don't want anyone to commit this file.
> Add a .gitignore to ignore doc/tags file

- ftdetect/jbuild.vim
- ftplugin/jbuild.vim
- syntax/jbuild.vim
Hi,
As mentioned in #15, this project currently lacks `jbuild` support.
This adds highlights toplevel stanzas and common parameters.
Thanks!
> Add a syntax for jbuild files

- ftplugin/ocaml.vim
This fixes the forward scan of %. Previously % would only work when the
cursor was on a matched word, since every other position would match the
empty entry.
> Remove empty entry from matchit words

- syntax/ocaml.vim
It is just a function in `Pervasives` and is otherwise a valid identifier.
> Remove "raise" from the list of keywords

- ftplugin/jbuild.vim
- syntax/jbuild.vim
Note the need for `syn iskeyword clear` for `#` and `?` to be recognized an keywords.  Let me know if you prefer a different option.  I also wondered whether the omission of `deps` and `targets` keys is intentional, since they are very common clauses.
> Add more keywords and match ${...} in jbuild syntax.

- ftplugin/ocaml.vim
The `goto` command can cause unintentional change of `jumplist`.
(For example, when reopen current buffer with `:edit!`.)
> remove needless `goto`

- syntax/opam.vim
now that description/synopsis are mandatory, they should definitely be highlighted
> add missing keywords to `opam.vim`

- compiler/ocaml.vim
- ftdetect/ocaml.vim
- ftplugin/jbuild.vim
- ftplugin/sexplib.vim
- syntax/ocaml.vim
- syntax/sexplib.vim
This is an attempt to resync files found [there](https://github.com/mmottl/vim-files/blob/master/.vim/) with their descendants here. Changes are indicated in bold.
Files which were modified only here (not updated by this PR):
+ *`ftdetect/ocaml.vim`* (except that I fixed a typo)
+ `ftplugin/ocaml.vim` (but what is the purpose of commit 0672bcf ?)
Files which were modified only there (fast‐forward updating):
+ **`compiler/ocaml.vim`**
+ **`syntax/sexplib.com`**
+ `ftdetect/sexplib.com`: I did not include the changes ([1](https://github.com/mmottl/vim-files/commit/42e809e6446fa755ff9bb5ad8d9ce32a4f446d86#diff-1be10d2e4e1c29c41820bde2b8c112c4), [2](https://github.com/mmottl/vim-files/commit/35ca5d16aeb442e4899fa5291328599d7811df20)) because they conflict with our `ftdetect/jbuild.vim` …
> Mirror changes from M. Mottl’s repository

- syntax/ocaml.vim
Until now, named parameters were highlighted in the following situations:
* `?name` accounts for these constructions:
+ simple optional λ-binders: `fun ?name -> expr`
+ optional parameter passing: `f ?name`, `f ?name:expr`
+ optional parameters in function types: `?name:typ -> typ`
* `?(name …)` accounts for these:
+ optional λ-binders with typing annotations and/or default values: `?(name : typ)`, `?(name = expr)`, `?(name : typ = expr)`.
* `~name` accounts for these:
+ simple non-optional λ-binders: `fun ~name -> expr`
+ non-optional parameter passing: `f ~name`, `f ~name:expr`
This commit adds highlighting in the following situation:
* `~(name …)` accounts for these:
+ non-optional λ-binders with typing annotations: `?(name : typ)`.
---
What is still missing is highlighting …
> Also highlight named parameters between parentheses

- syntax/ocaml.vim
This commit highlights 5 more preprocessing directives: `#load_rec`, `#mod_use`, `#list`, `#predicates`, `#camlp4r`. The first 2 are standard (I think?). The last 3 are Findlib directives.
> Add missing directives to `syntax/ocaml.vim`

- syntax/ocaml.vim
Until now, `struct/end` and `sig/end` pairs were highlighted just as module name, under the matchgroup `ocamlModule`. This may not be desirable aesthetically. For example, the user may want to show them as keywords.
This commit isolates these delimiters in new matchgroups `ocamlSigEncl` and `ocamlStructEncl`, so that the user can change their highlighting independently of that of module names. By default, these matchgroups link to `ocamlModule` so as to keep the same result.
This should be reviewed, as the code for parsing module-related stuff is quite complex and I didn’t understand all of it. I am pretty that what I have done is correct, but I might have missed occurences.
> Allow highlighting sig/end and struct/end differently from module names

- syntax/ocaml.vim
Ping @mmottl who showed interest in this (you can also check out the other PRs).
This PR reworks completely how OCaml operators are highlighted. Before this PR:
1. only a finite, small subset of operators were recognized; as a consequence:
+ not all operators were shown the same way: some were highlighted, some weren’t (most notably, `*` and `<` were highlighted but `+` and `/` weren’t);
+ in some operators, different characters had different styles (for example, only the tilde was highlighted in `~-`, only the star was highlighted in `*.`; and in `1--2`, the second minus sign was considered to be part of the integer literal);
2. some were matched as keywords;
3. all recognized operators were displayed with the same style as keywords.
With this PR:
1. (hopefully) all operators, as …
> Improve syntax highlighting for OCaml operators

- syntax/ocaml.vim
Since 4.08, in structures `open` behaves the same as include (from a syntax pov).
> syntax: add support for open struct

- syntax/ocaml.vim
Custom indexing operators were only highlighted in their “name” form (as in `( .![]<- ) a i v`), not in their “mixfix” form (as in `a.![i]<-v`). Moreover, no whitespace was tolerated before the `(`/`[`/`{` nor between the `)`/`]`/`}` and the `<-`, although OCaml allows it. Turns out it was easy to fix. So I fixed it.
Note that builtin indexers (`.()`, `.[]`, `.{}` and their `<-` counterpart), which are not operators, are still highlighted as keywords, as has always been the case.
> highlight indexing operators in mixfix position

- compiler/ocaml.vim
Even with `env OCAML_ERROR_STYLE=short`, OCaml can still produce errors with a range of lines, e.g.
File "lib_term/analysis.ml", lines 16-39, characters 8-26:
Error (warning 8): this pattern-matching is not exhaustive.
This might fix #35, but I've only tested it on one error so far.
> Update errorformat for OCaml >= 4.09

- syntax/ocaml.vim
This patch introduces new syntax group `ocamlDelimiter` used for matchgroup of start/end of `ocamlEncl` (parentheses, ...). Previously, this was set to `ocamlKeyword` that many other keywords like `match` belong to. I think parentheses deserve their own syntax/highlight group and they should be linked to `Delimiter` by default. 
Please feel free to change the default link to `ocamlKeyword` if you think it's better to keep the original default value.
> new syntax group for start/end of ocamlEncl

- ftplugin/ocaml.vim
- indent/ocaml.vim
Current tools like odoc and ocamlformat treat `*` as normal characters, not comment leaders, which can make them annoying.
With an empty leader continuing the comment from the first line doesn't preserve indentantion, this seems a problem with vim, for the rest of the cases it works as expected. Suggestion on how to work around this are very much welcome.
This setting can be overriden adding a line to the .vimrc / init.vim:
```
autocmd FileType ocaml setlocal comments=sr:(*,mb:*,ex:*)
```
I did not change the rest of `indent/ocaml.vim` due to my limited knowledge, it didn't seem to change the behaviour when I modified the section about comments. Let me know if a change is needed (and what kind of change should it be)
> Do not not insert * when adding a line to a comment.

- syntax/ocaml.vim
This enables to selectively highlight Keyword and Constructor delimiters.
I find that highlighting brackets and parentheses just adds to visual clutter for no real benefit and it would be nice if you could disable them.
> Put Constructor and Keyword delimiters in their own groups

- compiler/ocaml.vim
- One missing format for locations. `File "test.ml", line 1:`, used for signature mismatch errors.
- Skip highlighted code, which is otherwise joined to the error message.
- Match every other lines as "general messages" to make sure the quickfix window opens even if no messages matched.
> Improve error format

- doc/opam.txt
- ftdetect/opam.vim
- plugin/opam.vim
- syntax/opam.vim
on syntax, plugin & file detection
> Some opam updates

- syntax/ocaml.vim
What the title says. The first 2 commits are just simplifying or removing dead code. The second 2 are fixing 2 issues with highlighting.
1. It was intended that the `ocamlTopStop` matchgroup allowed the user to highlight `;;` differently than `;`, however that was not working; this is now fixed.
2. The code for highlighting shebangs wasn’t working anymore (because of a precedence conflict with newer code); this is now fixed, plus, the new `ocamlShebang` matchgroup allows the user to style shebangs to her liking (by default they are styled like comments, as before).
> Small cleanups and fixes

- plugin/opam.vim
The first commit fixes a typo from 03e925188.
The second commit add the `:Opam` command without argument, to refresh the environment without changing switch. This is useful when creating a switch or when the current switch has been changed from Opam's command directly.
> Improve :Opam command

- doc/opam.txt
- plugin/opam.vim
The previous change to :Opam carelessly used the equivalent of:
opam switch set $(opam switch show)
Which have an unexpected behavior in case of local or linked switches.
Now using a read only command equivalent to the intended:
eval $(opam env --readonly)
> Fix `:Opam` with local switches

- syntax/ocaml.vim
Tentative fix for issue #3 (partial, as the colon is still not linted as could be expected). But honestly, I’m not sure what I’m doing. The module linting code is “somewhat complicated stuff” indeed. Who wrote it?
I also sneaked in a few regex simplifications and what is perhaps another bugfix (`me=e-1` removes the last char of the match from the highlight, but I find it somewhat obscure and it can be meaningfully replaced by a look-ahead regex combinator; plus, it was missing in one place (when trying to match `(` not followed by `*`), which I think was a bug?).
> fix linting of nested functor application

- syntax/ocaml.vim
- type-linter-notes.md
- type-linter-test.ml
Each of the two commits fixes one the following issues (which were both noted as FIXMEs in the test file).
1. `exception E = F` : the equal sign was wrongly shown as an error; the fix is easy. This addresses a portion of #84.
2. `fun ... : t -> e` : the type context was wrongly running over `->` ; the fix introduces a little extra bit of complexity (`fun` is now the start of a region rather than just a keyword) but it is simpler than I anticipated (thanks to the `containedin=` feature of Vim). This closes #86.
Remaining issues:
- the test file has one remaining FIXME (but of much lesser importance, it is more a feature wish than an actual issue): `class ['a] myclass ...` where we’d like the type variable to be highlighted as such;
- #84 has one more issue: `(module M)` used as a type …
> Fix several linting issues related to the new linter

- syntax/opam.vim
Fix highlight for 'pin-depends' in opam syntax.
> fix highlight for pin-depends in opam syntax

- syntax/opam.vim
There is no difference between `opamKeyword1` and `opamKeyword2`.
related https://github.com/ocaml/vim-ocaml/pull/73#discussion_r801810302
> [opam] remove `opamKeyword2` 

- syntax/opam.vim
found the answer to https://github.com/ocaml/vim-ocaml/pull/73#discussion_r801810302 : `-` wasn't accepted in keywords. So setting it with `iskeyword` defined as `[a-z-]`
> [opam] accept keywords with dash

- syntax/ocaml.vim
This PR consists of incremental fixes and simplifications and is best reviewed per commit, with help from the (long) commit messages.
Although some of the bugs fixed were made obvious by the new type linter, they existed since the beginning of the Git history, years ago. The most notable bugfixes are:
* the linting of `module type of` (was not working in signatures);
* the linting of functor parameters `(X: T)` (was not working in signatures);
* the linting of the `functor` construct (was not working except in one situation).
Test suite for `module type of` (comments indicate behavior before this PR):
```ocaml
(* approximately ok:
*   - "module type of" linted as ocamlKeyword
*   - "F" linted as ocamlModule
*   - "(X)" linted meaninglessly but by chance it doesn’t look SO bad
*)
module N …
```
> Various fixes and improvements to module linting

- doc/opam.txt
- ftplugin/ocaml.vim
- plugin/opam.vim
This ensures that every Opam commands are in the same environment, the
'*PATH' variable are consistent with the switch used by commands in
':term' or ':!'.
Additionally, running a command directly won't differ from running it
through 'opam exec'.
The inconvenient is that the switch used might not be the selected
switch. Running 'opam switch set' won't affect subsequent commands at all.
The statusline function is already compatible with this: if ':Opam' is
ever called, it won't query `opam switch set` again, so it can be
simplified.
This is a draft PR because it might change how people use this plugin and Opam. For example, when using a shell along side vim (not inside) to run Opam commands, commands run inside Vim will be in the wrong environment.
I have seen `opam exec -- dune` commands …
> RFC: Make sure Opam's environment is consistent

- doc/opam.txt
- ftplugin/ocaml.vim
This was part of e775524 but was intended to be disabled when `g:opam_set_switch` isn't set.
> Opam: No startup call when g:opam_set_switch is disabled

- syntax/dune.vim
The title says it all.
By the way, I wondered whether such a simple change deserved a change line, but it might help keep track of changes across repositories (`vim`’s, this one, etc.)?
> Add dune syntax for end-of-line strings

- plugin/opam.vim
`:Opam <switch>` might not have an effect when `$OPAMSWITCH` is set (and `g:opam_set_switch` is not set) or when a local switch (or switch link) is present.
This prints the reason to avoid confusion.
> Opam: Print reason if switching didn't work

- syntax/opam.vim
It fixes the issue happening when a vairable is not terminated
```
post-messages: "installed version %{version"
```
As it is defined as a region, is it highlighted until next closing  `}%`
The PR offers fix that issue and to highlight the wrong (but as a fallback understood by opam) `%{var`
> opam: fix & highlight unterminated variables
